### ISSUE TITLE
Possible inaccuracies in the solution for Chapter 8 exercise 8th problem

### ISSUE THREAD

**Issue by Kacppian** [floatingyuzu/programming-abstractions#2]
In the question it was mentioned that the first character of the string has to be removed while I didn't find that in the solution provided. Could you please look into it? Thank you!

**Comment by floatingyuzu** [comment]
It looks like I removed the chapter 8 folder by mistake a couple years ago.  I added the file back and as far as I can tell it completes the exercise.  The general generatepermutations function is from the book and the generatepermutationsbyben is the one that solves the exercise - they both give the same result but with a different technique.
